import { TeamMember } from "../types";

export const teamMembers: TeamMember[] = [
    {
        id: 3,
        name: "Mwakwari", surname: "Mwata",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Mwata[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    // 4 and 5 are reserved female players
    {         
        id: 6,
        name: "Ezekiel", surname: "Safari Saro",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 7,
        name: "Omar", surname: "Masai",
        position: "Captain",
        imageUrl: "src/pages/about/teams/mens/media/masai[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 8,
        name: "Ibrahim", surname: "Chacha",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
  /*   {
        id: 9,
        name: "Ray", surname: "Fares",
        position: "Secretary",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: "35",
        weight: "135kgs",
    }, */
    {         
        id: 10,
        name: "Perez", surname: "Kombe",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 11,
        name: "Andrew", surname: "Nyakundi",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Andrew[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    //  there's no player id 12
    {
        id: 13,
        name: "Julius", surname: "Brighton",
        position: "Assistant Captain",
        imageUrl: "src/pages/about/teams/mens/media/julius[player].jpg",
        age: 23,
        weight: "96kgs",
    },
    {         
        id: 14,
        name: "Pascal", surname: "Chivatsi",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/pascal[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 15,
        name: "Aritasio", surname: "Kinyua",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {   // missing bingwafest picture    
        id: 16,
        name: "Navin", surname: "Allan",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 17,
        name: "Alex", surname: "Maina",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Alex[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 18,
        name: "Lemmy", surname: "Shume",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/lemmy[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 19,
        name: "Mutavi", surname: "Makau",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 20,
        name: "Tom", surname: "Wanje",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 21,
        name: "Kalama", surname: "Kazungu",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 22,
        name: "Mactor", surname: "Menza",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Mactor[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 23,
        name: "Samuel", surname: "Badiwa Komoro",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/samuel[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 24,
        name: "Desmond", surname: "Kavya",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Desmond[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 25,
        name: "Edward", surname: "Fondo",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/edward[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 26,
        name: "Kai", surname: "Sifa",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/Kai[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 27,
        name: "Derrick", surname: "Mwambire",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/derrick[player].jpg",
        age: 24,
        weight: "88kgs",
    },
    {         
        id: 28,
        name: "Fernando", surname: "Ochiel",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    },
/*     {         
        id: 29,
        name: "Benson", surname: "mwata",
        position: "player",
        imageUrl: "src/pages/about/teams/mens/media/dummy.jpg",
        age: 24,
        weight: "88kgs",
    }, */
];